service: nodejs-lambda-unit-tests
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  
plugins:
  - serverless-plugin-optimize
  - serverless-mocha-plugin

package:
  individually: true
  
functions:
  - ${file(src/functions/getAddressInfo/config.yml)}